### PR TITLE
Issue 149 bug bad array new length for steckler

### LINKED ISSUE #149: Bug: Bad array new length for steckler case
image

### PR DESCRIPTION
**Pull request by LinhWuerzburger**
closes #149

### CODE REVIEW

File: src/boundary/Multigrid.cpp [hunk 1]
```diff
@@ -779,62 +777,13 @@ Obstacle **Multigrid::obstacle_dominant_restriction(size_t level) {
         size = data.size();
     }
 
-    size_t *obstacle_list_tmp = new size_t[size];
+    auto *obstacle_list_tmp = new size_t[size];
```
Comment (ChristianVonMach) [inline src/boundary/Multigrid.cpp:780]: `auto *` looks redundant. does it need to be always a pointer or is a plain `auto` an option?

Comment (LinhWuerzburger) [reply src/boundary/Multigrid.cpp]: changed in d4f2721

File: src/boundary/Obstacle.h [hunk 2]
```diff
@@ -69,6 +69,7 @@ class Obstacle {
 
     bool is_corner_cell(size_t i, size_t j, size_t k);
     bool is_edge_cell(size_t i, size_t j, size_t k);
+    bool has_overlap(size_t i1, size_t i2, size_t j1, size_t j2, size_t k1, size_t k2);
```
[the remark this answers is not in the document]
Comment (LinhWuerzburger) [reply src/boundary/Obstacle.h]: changed in a986117

**Review by ChristianVonMach — APPROVED** [review]
